/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sesion3;

import java.util.Observable;

/**
 *
 * @author jose
 */
public class TiempoSatelital extends javax.swing.JFrame{

    /**
     * Creates new form ImageSetting
     */
    public TiempoSatelital(Observable madrid, Observable cadiz, Observable galicia) {
        System.out.println("MapaMeteorologico 1");
        initComponents();
        this.setVisible(true);
        madrid.addObserver((LabelObserver) this.tempMadrid);
        cadiz.addObserver((LabelObserver) this.tempCadiz);
        galicia.addObserver((LabelObserver) this.tempGalicia);
        System.out.println("MapaMeteorologico 2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tempMadrid = new LabelObserver();
        tempCadiz = new LabelObserver();
        tempGalicia = new LabelObserver();
        mapa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(508, 404));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(501, 0, 0, 0);

        tempMadrid.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        tempMadrid.setForeground(new java.awt.Color(235, 4, 4));
        tempMadrid.setText("jLabel2");
        tempMadrid.setMaximumSize(new java.awt.Dimension(148, 44));
        tempMadrid.setMinimumSize(new java.awt.Dimension(148, 44));
        getContentPane().add(tempMadrid);
        tempMadrid.setBounds(200, 160, 116, 47);

        tempCadiz.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        tempCadiz.setForeground(new java.awt.Color(245, 14, 14));
        tempCadiz.setText("jLabel2");
        getContentPane().add(tempCadiz);
        tempCadiz.setBounds(100, 280, 160, 60);

        tempGalicia.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        tempGalicia.setForeground(new java.awt.Color(253, 14, 14));
        tempGalicia.setText("jLabel2");
        getContentPane().add(tempGalicia);
        tempGalicia.setBounds(30, 30, 116, 47);

        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa.jpg"))); // NOI18N
        mapa.setText("jLabel1");
        getContentPane().add(mapa);
        mapa.setBounds(0, 0, 500, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mapa;
    private javax.swing.JLabel tempCadiz;
    private javax.swing.JLabel tempGalicia;
    private javax.swing.JLabel tempMadrid;
    // End of variables declaration//GEN-END:variables

}
