/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sesion4;

/**
 *
 * @author alejandro
 */
public class PanelBotones extends javax.swing.JFrame {

    AudiR8 coche;
    
    /**
     * Creates new form PanelBotones
     */
    public PanelBotones(AudiR8 coche) {
        initComponents();
        this.coche = coche;
        this.setVisible(true);
        this.actualizaEstado();
        this.BotonAcelerar.setText("ACELERAR");
        this.BotonFrenar.setText("FRENAR");
        this.BotonEncender.setText("ENCENDER");
        //this.BotonEncender
    }
    
    private void actualizaEstado() {
        this.EtiqMostrarEstado.setText(this.coche.getEstado().toString());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonEncender = new javax.swing.JToggleButton();
        BotonAcelerar = new javax.swing.JButton();
        BotonFrenar = new javax.swing.JButton();
        EtiqMostrarEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonEncender.setText("jToggleButton1");
        BotonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncenderActionPerformed(evt);
            }
        });

        BotonAcelerar.setText("jButton1");
        BotonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcelerarActionPerformed(evt);
            }
        });

        BotonFrenar.setText("jButton2");
        BotonFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFrenarActionPerformed(evt);
            }
        });

        EtiqMostrarEstado.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        EtiqMostrarEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiqMostrarEstado.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonEncender)
                        .addGap(18, 18, 18)
                        .addComponent(BotonAcelerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonFrenar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EtiqMostrarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiqMostrarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonEncender, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(BotonAcelerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonFrenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncenderActionPerformed
        if (this.coche.getEstado() == EstadoMotor.APAGADO) {
            this.coche.setEstado(EstadoMotor.ENCENDIDO);
            this.BotonEncender.setText("APAGAR");
        } else {
            this.coche.setEstado(EstadoMotor.APAGADO);
            this.BotonEncender.setText("ENCENDER");
            this.BotonAcelerar.setText("ACELERAR");
            this.BotonFrenar.setText("FRENAR");
        }
        this.actualizaEstado();
    }//GEN-LAST:event_BotonEncenderActionPerformed

    private void BotonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcelerarActionPerformed
        switch(this.coche.getEstado()) {
            case ACELERANDO:
                this.coche.setEstado(EstadoMotor.ENCENDIDO);
                this.BotonAcelerar.setText("ACELERAR");
                break;
            case FRENANDO: 
                this.BotonFrenar.setText("FRENAR");
            case ENCENDIDO:
                this.coche.setEstado(EstadoMotor.ACELERANDO);
                this.BotonAcelerar.setText("Soltar acelerador");
                break;
        }
        this.actualizaEstado(); 
    }//GEN-LAST:event_BotonAcelerarActionPerformed

    private void BotonFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFrenarActionPerformed
        switch(this.coche.getEstado()) {
            case FRENANDO:
                this.coche.setEstado(EstadoMotor.ENCENDIDO);
                this.BotonFrenar.setText("FRENAR");
                break;
            case ACELERANDO: 
                this.BotonAcelerar.setText("ACELERAR");
            case ENCENDIDO:
                this.coche.setEstado(EstadoMotor.FRENANDO);
                this.BotonFrenar.setText("Soltar freno");
                break;
        }
        this.actualizaEstado(); 
    }//GEN-LAST:event_BotonFrenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAcelerar;
    private javax.swing.JToggleButton BotonEncender;
    private javax.swing.JButton BotonFrenar;
    private javax.swing.JLabel EtiqMostrarEstado;
    // End of variables declaration//GEN-END:variables
}
