/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SCACV.MonitorConsumos;

/**
 *
 * @author jose
 */
public class ControlConsumibles extends javax.swing.JPanel {
    
    ControlConsumible controlAceite;
    ControlConsumible controlFrenos;
    ControlConsumible controlRevision;
    ControlConsumible controlCombustible;

    /**
     * Creates new form IndicadoresLuminosos
     */
    public ControlConsumibles(MonitorConsumos consumos) {
        initComponents();
        this.controlAceite = new ControlConsumible(consumos.getAceite(), "aceite");
        this.controlAceite.setBounds(0, 50, 400, 50);
        this.add(this.controlAceite);
        
        this.controlFrenos = new ControlConsumible(consumos.getFrenos(), "frenos");
        this.controlFrenos.setBounds(400, 0, 400, 50);
        this.add(this.controlFrenos);
        
        this.controlRevision = new ControlConsumible(consumos.getGeneral(), "revision");
        this.controlRevision.setBounds(400, 50, 400, 50);
        this.add(this.controlRevision);
        
        this.controlCombustible = new ControlConsumible(consumos.getGasolina(), "combustible");
        this.controlCombustible.setBounds(0,0, 400, 50);
        this.add(this.controlCombustible);
        
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
