/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utils.CarOperation;
import eu.hansolo.steelseries.gauges.Radial;
import java.awt.BorderLayout;

/**
 *
 * @author alejandro
 */
public class Contador extends javax.swing.JPanel {

    Radial indicador;
    
    /**
     * Creates new form Contador
     */
    public Contador(String title, int maxValue) {
        initComponents();
        
        this.indicador = new Radial();
        this.indicador.setTitle(title);
        this.indicador.setUnitString("0");
        this.indicador.setMaxValue(maxValue);
        
        this.setLayout(new BorderLayout());
        this.add(this.indicador, BorderLayout.CENTER);
        
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
