/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Car.AudiR8;
import Car.EstadoMotor;
import Car.SCACV.EstadoSCACV;
import java.awt.Color;

/**
 *
 * @author jose
 */
public class PanelBotones extends javax.swing.JPanel {

    AudiR8 coche;

    /**
     * Creates new form PanelBotones
     */
    public PanelBotones(AudiR8 coche) {
        initComponents();
        this.coche = coche;
        this.parametrosIniciales();
        this.actualizaInterfaz();
    }

    public void actualizaInterfaz() {

        if (this.coche.getSCACV().getEstadoSCACV() != EstadoSCACV.APAGADO) {
            this.EtiqMostrarEstado.setText(this.coche.getSCACV().getEstadoSCACV().toString());

            this.BotonAcelerar.setText("ACELERAR");
            this.BotonAcelerar.setSelected(false);
            this.BotonFrenar.setText("FRENAR");
            this.BotonFrenar.setSelected(false);
        } else {
            this.EtiqMostrarEstado.setText(this.coche.getEstado().toString());
            this.BotonMantener.setSelected(false);
            this.BotonReiniciar.setSelected(false);
            this.BotonAcelerarSCACV.setSelected(false);
        }
        
        switch (this.coche.getSCACV().getEstadoSCACV()) {
            case APAGADO:
                this.BotonAcelerarSCACV.setSelected(false);
                this.BotonMantener.setSelected(false);
                this.BotonReiniciar.setSelected(false);
                break;
            case ACELERANDO:
                this.BotonAcelerarSCACV.setSelected(true);
                this.BotonMantener.setSelected(false);
                this.BotonReiniciar.setSelected(false);
                break;
            case MANTENIENDO:
                this.BotonAcelerarSCACV.setSelected(false);
                this.BotonMantener.setSelected(true);
                this.BotonReiniciar.setSelected(false);
                break;
            case REINICIANDO:
                this.BotonAcelerarSCACV.setSelected(false);
                this.BotonMantener.setSelected(false);
                this.BotonReiniciar.setSelected(true);
                break;
        }

        if (this.BotonEncender.isSelected()) {
            this.BotonEncender.setForeground(Color.red);
        } else {
            this.BotonEncender.setForeground(Color.green);
        }

        if (this.BotonAcelerar.isSelected()) {
            this.BotonAcelerar.setForeground(Color.red);
        } else {
            this.BotonAcelerar.setForeground(Color.black);
        }

        if (this.BotonFrenar.isSelected()) {
            this.BotonFrenar.setForeground(Color.red);
        } else {
            this.BotonFrenar.setForeground(Color.black);
        }
    }

    public void actualizarEstado(Boolean sinGasolina) {
        if (sinGasolina) {
            this.parametrosIniciales();
        }
        this.BotonEncender.setEnabled(!sinGasolina);
        this.actualizaInterfaz();
    }

    public void parametrosIniciales() {
        this.EtiqMostrarEstado.setForeground(Color.red);
        this.BotonAcelerar.setText("ACELERAR");
        this.BotonAcelerar.setSelected(false);
        this.BotonFrenar.setText("FRENAR");
        this.BotonFrenar.setSelected(false);
        this.BotonEncender.setText("ENCENDER");
        this.BotonEncender.setSelected(false);
        this.BotonEncender.setForeground(Color.green);
    }

    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiqMostrarEstado = new javax.swing.JLabel();
        BotonEncender = new javax.swing.JToggleButton();
        BotonAcelerar = new javax.swing.JToggleButton();
        BotonFrenar = new javax.swing.JToggleButton();
        BotonMantener = new javax.swing.JToggleButton();
        BotonReiniciar = new javax.swing.JToggleButton();
        BotonAcelerarSCACV = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(387, 266));

        EtiqMostrarEstado.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        EtiqMostrarEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiqMostrarEstado.setText("jLabel1");

        BotonEncender.setText("encender/apagar");
        BotonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncenderActionPerformed(evt);
            }
        });

        BotonAcelerar.setText("acelerar");
        BotonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcelerarActionPerformed(evt);
            }
        });

        BotonFrenar.setText("frenar");
        BotonFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFrenarActionPerformed(evt);
            }
        });

        BotonMantener.setText("SCACV mantener");
        BotonMantener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMantenerActionPerformed(evt);
            }
        });

        BotonReiniciar.setText("SCACV reiniciar");
        BotonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReiniciarActionPerformed(evt);
            }
        });

        BotonAcelerarSCACV.setText("SCACV acelelarar");
        BotonAcelerarSCACV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcelerarSCACVActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("SCACV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(BotonEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EtiqMostrarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(BotonFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(BotonAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonReiniciar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(BotonMantener))
                    .addComponent(BotonAcelerarSCACV))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonMantener, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonAcelerarSCACV, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BotonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EtiqMostrarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncenderActionPerformed
        this.coche.getSCACV().setEstadoSCACV(EstadoSCACV.APAGADO);

        if (this.coche.getEstado() == EstadoMotor.APAGADO) {
            this.coche.setEstado(EstadoMotor.ENCENDIDO);
            this.BotonEncender.setText("APAGAR");
        } else {
            this.coche.setEstado(EstadoMotor.APAGADO);
            this.BotonEncender.setText("ENCENDER");
            this.BotonAcelerar.setText("ACELERAR");
            this.BotonFrenar.setText("FRENAR");
            this.BotonMantener.setSelected(false);
            this.BotonAcelerar.setSelected(false);
            this.BotonFrenar.setSelected(false);
        }
        this.actualizaInterfaz();
    }//GEN-LAST:event_BotonEncenderActionPerformed

    private void BotonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcelerarActionPerformed
        if (this.coche.getSCACV().getEstadoSCACV() != EstadoSCACV.APAGADO) {
            this.coche.setEstado(EstadoMotor.ENCENDIDO);
        }
        
        this.coche.getSCACV().setEstadoSCACV(EstadoSCACV.APAGADO);

        switch (this.coche.getEstado()) {
            case ACELERANDO:
                this.coche.setEstado(EstadoMotor.ENCENDIDO);
                this.BotonAcelerar.setText("ACELERAR");
                break;
            case FRENANDO:
                this.BotonFrenar.setText("FRENAR");
                this.BotonFrenar.setSelected(false);
            case ENCENDIDO:
                this.coche.setEstado(EstadoMotor.ACELERANDO);
                this.BotonAcelerar.setText("Soltar acelerador");
                break;
            case APAGADO:
                this.BotonAcelerar.setSelected(false);
                break;
        }
        this.actualizaInterfaz();
    }//GEN-LAST:event_BotonAcelerarActionPerformed

    private void BotonFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFrenarActionPerformed
        if (this.coche.getSCACV().getEstadoSCACV() != EstadoSCACV.APAGADO) {
            this.coche.setEstado(EstadoMotor.ENCENDIDO);
        }
        
        this.coche.getSCACV().setEstadoSCACV(EstadoSCACV.APAGADO);
        switch (this.coche.getEstado()) {
            case FRENANDO:
                this.coche.setEstado(EstadoMotor.ENCENDIDO);
                this.BotonFrenar.setText("FRENAR");
                break;
            case ACELERANDO:
                this.BotonAcelerar.setText("ACELERAR");
                this.BotonAcelerar.setSelected(false);
            case ENCENDIDO:
                this.coche.setEstado(EstadoMotor.FRENANDO);
                this.BotonFrenar.setText("Soltar freno");
                break;
            case APAGADO:
                this.BotonFrenar.setSelected(false);
                break;
        }
        this.actualizaInterfaz();
    }//GEN-LAST:event_BotonFrenarActionPerformed

    private void BotonMantenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMantenerActionPerformed
        if (this.coche.getEstado() == EstadoMotor.APAGADO) {
            this.BotonMantener.setSelected(false);
        }else if (this.coche.getSCACV().getEstadoSCACV() == EstadoSCACV.MANTENIENDO) {
            this.coche.getSCACV().setEstadoSCACV(EstadoSCACV.APAGADO);
        } else {
            this.coche.getSCACV().setEstadoSCACV(EstadoSCACV.MANTENIENDO);
        }
        
        this.actualizaInterfaz();
    }//GEN-LAST:event_BotonMantenerActionPerformed

    private void BotonAcelerarSCACVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcelerarSCACVActionPerformed
        if (this.coche.getEstado() == EstadoMotor.APAGADO) {
            this.BotonAcelerarSCACV.setSelected(false);
        }else if (this.coche.getSCACV().getEstadoSCACV() == EstadoSCACV.ACELERANDO) {
            this.coche.getSCACV().setEstadoSCACV(EstadoSCACV.APAGADO);
        } else {
            this.coche.getSCACV().setEstadoSCACV(EstadoSCACV.ACELERANDO);
        }
        this.actualizaInterfaz();
    }//GEN-LAST:event_BotonAcelerarSCACVActionPerformed

    private void BotonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReiniciarActionPerformed
        if (this.coche.getEstado() == EstadoMotor.APAGADO) {
            this.BotonReiniciar.setSelected(false);
        }else if (this.coche.getSCACV().getEstadoSCACV() == EstadoSCACV.REINICIANDO) {
            this.coche.getSCACV().setEstadoSCACV(EstadoSCACV.APAGADO);
        } else {
            this.coche.getSCACV().setEstadoSCACV(EstadoSCACV.REINICIANDO);
        }
        this.actualizaInterfaz();
    }//GEN-LAST:event_BotonReiniciarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAcelerar;
    private javax.swing.JToggleButton BotonAcelerarSCACV;
    private javax.swing.JToggleButton BotonEncender;
    private javax.swing.JToggleButton BotonFrenar;
    private javax.swing.JToggleButton BotonMantener;
    private javax.swing.JToggleButton BotonReiniciar;
    private javax.swing.JLabel EtiqMostrarEstado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
