/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SCACV.AudiR8;
import SCACV.EstadoMotor;
import java.awt.Color;

/**
 *
 * @author jose
 */
public class PanelBotones extends javax.swing.JPanel {
 AudiR8 coche;
    
    /**
     * Creates new form PanelBotones
     */
    public PanelBotones(AudiR8 coche) {
        initComponents();
        this.coche = coche;
        this.actualizaInterfaz();
        this.EtiqMostrarEstado.setForeground(Color.red);
        this.BotonAcelerar.setText("ACELERAR");
        this.BotonFrenar.setText("FRENAR");
        this.BotonEncender.setText("ENCENDER");
        this.BotonEncender.setForeground(Color.green);
    }
    
    public void actualizaInterfaz() {
        this.EtiqMostrarEstado.setText(this.coche.getEstado().toString());
        
        if(this.BotonEncender.isSelected()){
            this.BotonEncender.setForeground(Color.red);
        } else {
            this.BotonEncender.setForeground(Color.green);
        }
        
        if(this.BotonAcelerar.isSelected()){
            this.BotonAcelerar.setForeground(Color.red);
        } else {
            this.BotonAcelerar.setForeground(Color.black);
        }
        
        if(this.BotonFrenar.isSelected()){
            this.BotonFrenar.setForeground(Color.red);
        } else {
            this.BotonFrenar.setForeground(Color.black);
        }
    }
    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiqMostrarEstado = new javax.swing.JLabel();
        BotonEncender = new javax.swing.JToggleButton();
        BotonAcelerar = new javax.swing.JToggleButton();
        BotonFrenar = new javax.swing.JToggleButton();

        EtiqMostrarEstado.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        EtiqMostrarEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiqMostrarEstado.setText("jLabel1");

        BotonEncender.setText("jToggleButton1");
        BotonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncenderActionPerformed(evt);
            }
        });

        BotonAcelerar.setText("jToggleButton1");
        BotonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcelerarActionPerformed(evt);
            }
        });

        BotonFrenar.setText("jToggleButton1");
        BotonFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFrenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonEncender)
                        .addGap(18, 18, 18)
                        .addComponent(BotonAcelerar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonFrenar))
                    .addComponent(EtiqMostrarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiqMostrarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncenderActionPerformed
        if (this.coche.getEstado() == EstadoMotor.APAGADO) {
            this.coche.setEstado(EstadoMotor.ENCENDIDO);
            this.BotonEncender.setText("APAGAR");
        } else {
            this.coche.setEstado(EstadoMotor.APAGADO);
            this.BotonEncender.setText("ENCENDER");
            this.BotonAcelerar.setText("ACELERAR");
            this.BotonFrenar.setText("FRENAR");
            this.BotonAcelerar.setSelected(false);
            this.BotonFrenar.setSelected(false);
        }
        this.actualizaInterfaz();
    }//GEN-LAST:event_BotonEncenderActionPerformed

    private void BotonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcelerarActionPerformed
        switch(this.coche.getEstado()) {
            case ACELERANDO:
            this.coche.setEstado(EstadoMotor.ENCENDIDO);
            this.BotonAcelerar.setText("ACELERAR");
            break;
            case FRENANDO:
            this.BotonFrenar.setText("FRENAR");
            this.BotonFrenar.setSelected(false);
            case ENCENDIDO:
            this.coche.setEstado(EstadoMotor.ACELERANDO);
            this.BotonAcelerar.setText("Soltar acelerador");
            break;
            case APAGADO:
            this.BotonAcelerar.setSelected(false);
            break;
        }
        this.actualizaInterfaz();
    }//GEN-LAST:event_BotonAcelerarActionPerformed

    private void BotonFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFrenarActionPerformed
        switch(this.coche.getEstado()) {
            case FRENANDO:
            this.coche.setEstado(EstadoMotor.ENCENDIDO);
            this.BotonFrenar.setText("FRENAR");
            break;
            case ACELERANDO:
            this.BotonAcelerar.setText("ACELERAR");
            this.BotonAcelerar.setSelected(false);
            case ENCENDIDO:
            this.coche.setEstado(EstadoMotor.FRENANDO);
            this.BotonFrenar.setText("Soltar freno");
            break;
            case APAGADO:
            this.BotonFrenar.setSelected(false);
            break;
        }
        this.actualizaInterfaz();
    }//GEN-LAST:event_BotonFrenarActionPerformed
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        System.exit(0);
    }                            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAcelerar;
    private javax.swing.JToggleButton BotonEncender;
    private javax.swing.JToggleButton BotonFrenar;
    private javax.swing.JLabel EtiqMostrarEstado;
    // End of variables declaration//GEN-END:variables
}
