/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utils.CarOperation;
import eu.hansolo.steelseries.gauges.Radial;
import java.awt.BorderLayout;

/**
 *
 * @author super
 */
public class Velocimetro extends javax.swing.JPanel {
    
    Radial gauge;
    
    /**
     * Creates new form Velocimetro
     */
    public Velocimetro() {
        initComponents();
        this.gauge = new Radial();
        this.gauge.setTitle("Velocimetro");
        this.gauge.setUnitString("0");
        this.gauge.setMaxValue(300);
        
        this.setLayout(new BorderLayout());
        this.add(this.gauge, BorderLayout.CENTER);
        
        this.setVisible(true);
    }

    public double actualiza(double revoluciones, double radioEje) {
        double velocidad = CarOperation.velocidad(revoluciones, radioEje);
        this.gauge.setValueAnimated(velocidad);
        this.gauge.setUnitString(Double.toString(velocidad));
        return velocidad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
