/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SCACV;

/**
 *
 * @author super
 */
public class CuentaKilometros extends javax.swing.JPanel {

    double kilometrosTotales = 0.0;
    double kilometrosParciales = 0.0;
    
    double timeSinceStart = System.nanoTime() / 1000;
    double oldTimeSinceStart = 0.0;
    double deltaTime = 0.0;
    
    /**
     * Creates new form CuentaKilometros
     */
    public CuentaKilometros() {
        initComponents();
        this.setVisible(true);
    }
    
    public void actualizar(double velocidad, EstadoMotor estadoMotor) {
        this.actualizaReloj();
        
        double kilometrosAndados = velocidad / 3600; //velocidad-> km/s
        kilometrosAndados *= this.deltaTime;
        
        
        if (estadoMotor == EstadoMotor.APAGADO)
            this.kilometrosParciales = 0.0;
        else
            this.kilometrosParciales += kilometrosAndados;
        
        this.kilometrosTotales += kilometrosAndados;
        // Tras hacer  las cuentas
        this.contadorReciente.setText(Double.toString(this.kilometrosParciales));
        this.contadorTotal.setText(Double.toString(kilometrosTotales));
    }
    
    private void actualizaReloj() {
        this.timeSinceStart = System.nanoTime() / 1000000000.0;
        this.deltaTime = this.timeSinceStart - this.oldTimeSinceStart;
        this.oldTimeSinceStart = this.timeSinceStart;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contadorReciente = new javax.swing.JLabel();
        contadorTotal = new javax.swing.JLabel();

        jLabel1.setText("Cuentakilómetros");

        jLabel2.setText("Contador total");

        jLabel3.setText("Contador reciente");

        contadorReciente.setText("0.0");

        contadorTotal.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contadorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(contadorReciente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(contadorReciente)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contadorTotal)
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel3)
                    .addContainerGap(106, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contadorReciente;
    private javax.swing.JLabel contadorTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
